name: Appium Mobile Tests

on:
  push:
  workflow_dispatch:

jobs:
  appium-test:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Appium tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 35
          target: google_apis
          arch: x86_64

          script: |
            echo "Starting Android emulator..."
            adb devices

            echo "Installing HCJ APK..."
            adb install apk/Hcj_Student_Jobseeker.apk

            echo "Starting Appium..."
            npx appium > appium.log 2>&1 &

            sleep 10

            echo "Running Appium tests..."
            npm test